// Passive-piezo buzzer driver with an RTTTL melody player.
//
// Tones are generated by the LEDC peripheral on PIN_BUZZER (a square wave at the
// note frequency, 50% duty). Playback runs in its own task so callers just kick
// off a melody and forget it; the alarm loops a melody until it's stopped.
//
// RTTTL is the old Nokia ringtone text format:
//   "Name:d=4,o=5,b=125:8e6,8d6,f#5,..."  (defaults then comma-separated notes)
#pragma once

#include <stdbool.h>
#include <stdint.h>

// Configure the LEDC timer/channel. Call once at boot.
void buzzer_init(void);

// Play an RTTTL string. If loop is true it repeats until buzzer_stop().
// Starting a new melody replaces any currently playing one.
void buzzer_play_rtttl(const char *rtttl, bool loop);

// Stop playback and silence the buzzer.
void buzzer_stop(void);

// True while a melody is playing.
bool buzzer_is_playing(void);

// Built-in melody table for the alarm (index wraps). Count is BUZZER_MELODY_COUNT.
#define BUZZER_MELODY_COUNT 8
const char *buzzer_builtin_rtttl(int index);
